Added new e-mail domains
elyby/anti-tempmail-repo pull request #2
Opened 2016-11-17 20:25 UTC by Nik-mmzd

Проверяй, Эрик ;)

2016-11-17 20:26 UTC, erickskrauch commented
Нехороший человек, а зачем ты четверной пробел заменил двойным?

2016-11-17 20:27 UTC, Nik-mmzd commented
Ну Ээээээрик... Как-то на автомате, ща поправим :D

2016-11-17 20:30 UTC, erickskrauch commented
Многие из добавленных доменов можно объединить регулярными выражениями.

2016-11-17 20:30 UTC, Nik-mmzd commented
@erickskrauch вот теперь точно все, чекай

2016-11-17 20:31 UTC, Nik-mmzd commented
Ну окай, но это тогда уже завтра. Тебе блин навстречу идут, а ты ворчишь :Ъ

2016-11-17 21:41 UTC, erickskrauch requested changes
Я пометил не все места, но суть, думаю, ясна. Нужно обобщить все домены, а не перечислять всевозможные найденные их вариации.

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "zombo\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "trump\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "uk\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "shitaway\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "purple\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "pw\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-17 21:41 UTC, erickskrauch commented on data.json
> +    "napalm51\\.(cf|ga|gq|igg\\.biz|ml|(nut|usa|flu|igg)\\.cc)",
Думаю лучше просто запретить любые продолжения этого домена

2016-11-18 08:45 UTC, erickskrauch approved these changes

2016-11-18 08:55 UTC, erickskrauch requested changes

2016-11-18 08:55 UTC, erickskrauch commented on data.json
> +    "[\\w]+\\.(mintemail\\.com)",
Ты уверен, что круглые скобки необходимы?

2016-11-18 08:55 UTC, erickskrauch commented on data.json
> +    "10minutemail\\.(co\\.za|com)",
Давай тоже обобщим на любой домен верхнего уровня.

2016-11-18 08:57 UTC, Nik-mmzd commented on data.json
> +    "[\\w]+\\.(mintemail\\.com)",
Это не я делал :D https://github.com/Nik-mmzd/anti-tempmail-repo/blob/master/data.json#L16

2016-11-18 10:56 UTC, erickskrauch approved these changes

2016-11-18 11:05 UTC, merged